### ISSUE TITLE
rake実行時にエラーが発生しました。

### ISSUE THREAD

**Issue by hayashi01** [raccy/dxruby_x64#2]
・rake実行時に以下のエラーが発生しました。
make: *** [Makefile:242: sound.o] エラー 1
rake aborted!

このエラーを解消する何かいい方法はございますでしょうか。

**Comment by raccy** [comment]
現象を確認しました。

以前は`GetObject`でエラーになったため`_GetObject`にしていたのが不要になったようです。GCCのバージョンかDirectXのSDKのバージョンが上がったのかも知れませんが、よくわかりません。

最新のコードでは修正されていますので、再度試して下さい。
